### ISSUE TITLE
Compatible with Tarantula RS?

### ISSUE THREAD

**Issue by jjrricardo** [lachusmadeti/Tarantula-Pro#1]
Can this firmware be used on the Tarantula RS?

**Comment by lachusmadeti** [comment]
Hi,

No, but if you give me the model board, drivers and screen I make it.

Best regards.

**Comment by lachusmadeti** [comment]
Ok,

I get it, MKS SGEN L v1.0, MKS TFT 24 v1.0 TP, TMC2208 and ¿dual Z axis?

Confirm please.

**Comment by jjrricardo** [comment]
Hello, that's right dual, this is the link model, thanks for the help.

https://homers3dprinter.com/products/copy-of-homers-odyssues-tevo-tarantula-pro-the-most-affordable-3d-printer-diy-kits-in-2020-newest-3d-printer


________________________________
De: Javier Fernández <notifications@github.com>
Enviado: quinta-feira, 13 de agosto de 2020 8:26 PM
Para: lachusmadeti/Tarantula-Pro
Cc: jjrricardo; Author
Assunto: Re: [lachusmadeti/Tarantula-Pro] Compatible with Tarantula RS? (#1)


Ok,

I get it, MKS SGEN L v1.0, MKS TFT 24 v1.0 TP, TMC2208 and ¿dual Z axis?

Confirm please.

**Comment by lachusmadeti** [comment]
Ok, give me some days for work on it.

Best regards

**Comment by lachusmadeti** [comment]
I have to start from 0, after receive images and info from other users of Tarantula RS, they (Homers/Tevo) announced wrong hardware, board seem´s SKR 1.3, and the drivers are configured as SPI connection, impossible they are TMC2208 (UART).

**Comment by lachusmadeti** [comment]
I close the issue, uploaded files for two RS models, with BTT SKR 1.3 board and MKS SGEN L v1.0 board.

Best regards.
