### ISSUE TITLE
factory firmware for Tarantula Pro with BLTouch enabled

### ISSUE THREAD

**Issue by frankTopspin** [lachusmadeti/Tarantula-Pro#2]
Hi Javier, thanks for this repository. Sorry if I'm writing here but I cannot find a way to contact you (email).
I'd like to know if the firmware that you have named "stock" is exactly the same that comes with the Tarantula Pro machine by Homers.
I've recently bought a Tarantula Pro with MKS Sgen L v1.0 and I don't know how backup the original firmware before put on it a new one.
Thanks 
Regards

**Comment by whitewhidow** [comment]
i have basically the same issue, there is no way to backup the current firmware, and there are clear differences between
- tevos offered firmware that is 2 years old 
- marlins example config for the tpp (has wrong board and other settings)
- the 'stock' config in this repo

so now im afraid to get the new 2.0.8 and adapt it for the tpp, as i have no idea what to actually change and what the values are etc ...       and no way to go back to the true, current, actual, 'stock' fw that it came shipped with

**Comment by lachusmadeti** [comment]
Hi!!!

the original firmware it's a old version, (2.0.5) without BLTocuh enabled, is impossible to back up the original firmware from the board.
My stock is with the same factory configuration, but with plus functions.
I don't have a working BLTouch now for made the changes, I always use manual level bed every two weeks.

Best regards.
