### ISSUE TITLE
any chance of a 2.0.8 version ?

### ISSUE THREAD

**Issue by whitewhidow** [lachusmadeti/Tarantula-Pro#3]
any chance of a 2.0.8 version ?

Thank you in advance!
Kind regards

**Comment by lachusmadeti** [comment]
Hi!!

sorry for late reply, I have some health problems, the next week I will release the new versions.

Best regards.

**Comment by whitewhidow** [comment]
hi,  no worries,   it is no longer needed atm,   have already updated to 2.0.8 with touch and dualz, only thing missing is power loss recovery but thats not a problem for me.  thx
